package com.iantapply.orchestra.adapter.postgres;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.iantapply.orchestra.api.EventStatus;
import com.iantapply.orchestra.audit.AuditEntry;
import com.iantapply.orchestra.domain.EventExecution;
import java.sql.Connection;
import java.sql.Statement;
import java.time.Instant;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import javax.sql.DataSource;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class PostgresRepositoriesTest {
    private DataSource dataSource;

    @BeforeEach
    void createSchema() throws Exception {
        JdbcDataSource h2 = new JdbcDataSource();
        h2.setURL("jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        dataSource = h2;
        try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE event_executions (
                        id uuid PRIMARY KEY, definition_id varchar(64) NOT NULL, status varchar(24) NOT NULL,
                        stage_index integer NOT NULL, version bigint NOT NULL, created_at timestamp NOT NULL,
                        updated_at timestamp NOT NULL, due_at timestamp, stage_started_at timestamp,
                        variables bytea NOT NULL, completed_actions bytea NOT NULL, failure text)
                    """);
            statement.execute("""
                    CREATE TABLE audit_log (
                        sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        occurred_at timestamp NOT NULL, actor varchar(128) NOT NULL, action varchar(96) NOT NULL,
                        resource varchar(256) NOT NULL, detail text NOT NULL, remote_address varchar(64))
                    """);
        }
    }

    @Test
    void executionRepositoryRoundTripsQueriesAndCompareAndSet() {
        PostgresExecutionRepository repository = new PostgresExecutionRepository(dataSource);
        Instant now = Instant.parse("2026-08-04T12:00:00Z");
        EventExecution execution = new EventExecution(
                UUID.randomUUID(),
                "event",
                EventStatus.SCHEDULED,
                -1,
                0,
                now,
                now,
                now,
                null,
                Map.of("number", 2),
                Set.of("done"),
                null);

        repository.create(execution);

        assertEquals(execution, repository.find(execution.id()).orElseThrow());
        assertEquals(java.util.List.of(execution), java.util.List.copyOf(repository.findDue(now, 10)));
        assertEquals(java.util.List.of(execution), java.util.List.copyOf(repository.findActive(10)));
        EventExecution replacement = execution.withVariables(Map.of("number", 3), now.plusSeconds(1));
        assertFalse(repository.compareAndSet(9, replacement));
        assertTrue(repository.compareAndSet(0, replacement));
        assertEquals(replacement, repository.find(execution.id()).orElseThrow());
        assertThrows(IllegalStateException.class, () -> repository.create(execution));
    }

    @Test
    void auditRepositoryReturnsNewestEntriesAndBoundsLimits() {
        PostgresAuditRepository repository = new PostgresAuditRepository(dataSource);
        AuditEntry first = new AuditEntry(Instant.EPOCH, "one", "start", "event", "first", null);
        AuditEntry second = new AuditEntry(Instant.EPOCH.plusSeconds(1), "two", "stop", "event", "second", "remote");

        repository.append(first);
        repository.append(second);

        assertEquals(java.util.List.of(second, first), repository.recent(10));
        assertEquals(java.util.List.of(second), repository.recent(1));
    }

    @Test
    void settingsRejectNonPostgresUrlsAndInvalidPoolSizes() {
        assertThrows(IllegalArgumentException.class, () -> new PostgresSettings("jdbc:h2:mem:test", "user", "pass", 1));
        assertThrows(
                IllegalArgumentException.class,
                () -> new PostgresSettings("jdbc:postgresql://localhost/db", "user", "pass", 0));
    }
}
