name: Build on Latest and All Platforms

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  ubuntu:
    name: Build Ubuntu Latest
    runs-on: ubuntu-latest
    environment: jdk25-building
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.UBUNTU_DISTRIBUTION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: bash ./gradlew clean lint test jar javadoc --no-daemon

  macos:
    name: Build macOS Latest
    runs-on: macos-latest
    environment: jdk25-building
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.MACOS_DISTRIBUTION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: bash ./gradlew clean lint test jar javadoc --no-daemon

  windows:
    name: Build Windows Latest
    runs-on: windows-latest
    environment: jdk25-building
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.WINDOWS_DISTRIBUTION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: .\gradlew.bat clean lint test jar javadoc --no-daemon
